import Head from "next/head";
import * as React from "react";
import {
  HomeDescktopComp,
  HomeInfo,
  HomeFood,
  HomeFoodsByCt,
} from "@/components/home";
import { Container, Stack } from "@mui/material";
import { useState } from "react";

const Home = () => {
  return (
    <>
      <Head>
        <title>Food Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.svg" />
      </Head>

      <Stack
        width={"100%"}
        sx={{ backgroundColor: "#FFF" }}
        alignItems={"flex-start"}
        marginBottom={"120px"}
      >
        <HomeDescktopComp />
        <Container maxWidth={"xl"} sx={{ width: "1306px" }}>
          <Stack>
            <HomeInfo />
            <HomeFood />
          </Stack>
          <Stack>
            <HomeFoodsByCt />
          </Stack>
        </Container>
      </Stack>
    </>
  );
};
export default Home;
