import Head from "next/head";
import * as React from "react";
import { HomeComp } from "@/components/home";

const Home = () => {
  return (
    <>
      <Head>
        <title>Food Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.svg" />
      </Head>
      <main>
        <HomeComp />
      </main>
    </>
  );
};
export default Home;
