export const CardDataFood = [
  {
    name: "Өглөөний хоол",
    price: 14800,
    saleProcent: 0,
    image: "/cardPic/cardPic1.jfif",
    ingridient: "Хулуу, төмс, лууван , сонгино, цөцгийн тос, самрын үр",
    category: "Үндсэн хоол",
    stock: 100,
  },
  {
    name: "Өглөөний хоол",
    price: 14800,
    saleProcent: 20,
    image: "/cardPic/cardPic1.jfif",
    ingridient: "Хулуу, төмс, лууван , сонгино, цөцгийн тос, самрын үр",
    category: "Үндсэн хоол",
    stock: 100,
  },
  {
    name: "Өглөөний хоол",
    price: 14800,
    saleProcent: 0,
    image: "/cardPic/cardPic1.jfif",
    ingridient: "Хулуу, төмс, лууван , сонгино, цөцгийн тос, самрын үр",
    category: "Үндсэн хоол",
    stock: 100,
  },
  {
    name: "Өглөөний хоол",
    price: 14800,
    saleProcent: 20,
    image: "/cardPic/cardPic1.jfif",
    ingridient: "Хулуу, төмс, лууван , сонгино, цөцгийн тос, самрын үр",
    category: "Үндсэн хоол",
    stock: 100,
  },
  {
    name: "Өглөөний хоол",
    price: 14800,
    saleProcent: 0,
    image: "/cardPic/cardPic1.jfif",
    ingridient: "Хулуу, төмс, лууван , сонгино, цөцгийн тос, самрын үр",
    category: "Үндсэн хоол",
    stock: 100,
  },
  {
    name: "Өглөөний хоол",
    price: 14800,
    saleProcent: 0,
    image: "/cardPic/cardPic1.jfif",
    ingridient: "Хулуу, төмс, лууван , сонгино, цөцгийн тос, самрын үр",
    category: "Салад ба зууш",
    stock: 100,
  },
  {
    name: "Өглөөний хоол",
    price: 14800,
    saleProcent: 20,
    image: "/cardPic/cardPic1.jfif",
    ingridient: "Хулуу, төмс, лууван , сонгино, цөцгийн тос, самрын үр",
    category: "Салад ба зууш",
    stock: 100,
  },
  {
    name: "Өглөөний хоол",
    price: 14800,
    saleProcent: 0,
    image: "/cardPic/cardPic1.jfif",
    ingridient: "Хулуу, төмс, лууван , сонгино, цөцгийн тос, самрын үр",
    category: "Салад ба зууш",
    stock: 100,
  },
  {
    name: "Өглөөний хоол",
    price: 14800,
    saleProcent: 0,
    image: "/cardPic/cardPic1.jfif",
    ingridient: "Хулуу, төмс, лууван , сонгино, цөцгийн тос, самрын үр",
    category: "Салад ба зууш",
    stock: 100,
  },
  {
    name: "Өглөөний хоол",
    price: 14800,
    saleProcent: 20,
    image: "/cardPic/cardPic1.jfif",
    ingridient: "Хулуу, төмс, лууван , сонгино, цөцгийн тос, самрын үр",
    category: "Амттан",
    stock: 100,
  },
  {
    name: "Өглөөний хоол",
    price: 14800,
    saleProcent: 0,
    image: "/cardPic/cardPic1.jfif",
    ingridient: "Хулуу, төмс, лууван , сонгино, цөцгийн тос, самрын үр",
    category: "Амттан",
    stock: 100,
  },
  {
    name: "Өглөөний хоол",
    price: 14800,
    saleProcent: 0,
    image: "/cardPic/cardPic1.jfif",
    ingridient: "Хулуу, төмс, лууван , сонгино, цөцгийн тос, самрын үр",
    category: "Амттан",
    stock: 100,
  },
  {
    name: "Өглөөний хоол",
    price: 14800,
    saleProcent: 0,
    image: "/cardPic/cardPic1.jfif",
    ingridient: "Хулуу, төмс, лууван , сонгино, цөцгийн тос, самрын үр",
    category: "Амттан",
    stock: 100,
  },
];

export const CardDataComertial = [
  {
    title: "Хүргэлтийн төлөв хянах",
    text: "Захиалга бэлтгэлийн явцыг хянах",
    icon: "/icons/Book.png",
  },
  {
    title: "Хүргэлтийн төлөв хянах",
    text: "Захиалга бэлтгэлийн явцыг хянах",
    icon: "/icons/Clock.png",
  },
  {
    title: "Хүргэлтийн төлөв хянах",
    text: "Захиалга бэлтгэлийн явцыг хянах",
    icon: "/icons/Food.png",
  },
  {
    title: "Хүргэлтийн төлөв хянах",
    text: "Захиалга бэлтгэлийн явцыг хянах",
    icon: "/icons/Book.png",
  },
];
export const CategoryData = [
  {
    name: "Хямдралтай",
    id: 1,
  },
  {
    name: "Үндсэн хоол",
    id: 2,
  },
  {
    name: "Салад ба зууш",
    id: 3,
  },
  {
    name: "Амттан",
    id: 4,
  },
];
